git clone git://github.com/MicrosoftLearning/AI-100-Design-Implement-Azure-AISol.git
git clone git://github.com/MicrosoftLearning/AI-102-AIEngineer.git
git clone git://github.com/MicrosoftLearning/AI-102-Code-Repos.git
git clone git://github.com/MicrosoftLearning/AI-102-LUIS.git
git clone git://github.com/MicrosoftLearning/AI-102-Process-Speech.git
git clone git://github.com/MicrosoftLearning/AZ-010-Azure-Administration-for-AWS-SysOps.git
git clone git://github.com/MicrosoftLearning/AZ-020-Microsoft-Azure-solutions-for-AWS-developers.git
git clone git://github.com/MicrosoftLearning/AZ-030T00-Microsoft-Azure-technologies-for-AWS-architects.git
git clone git://github.com/MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment.git
git clone git://github.com/MicrosoftLearning/AZ-101-MicrosoftAzureIntegrationandSecurity.git
git clone git://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator.git
git clone git://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.git
git clone git://github.com/MicrosoftLearning/AZ-120-Planning-and-Administering-Microsoft-Azure-for-SAP-Workloads.git
git clone git://github.com/MicrosoftLearning/AZ-140-Configuring-and-Operating-Windows-Virtual-Desktop.git
git clone git://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure.git
git clone git://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.git
git clone git://github.com/MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer.git
git clone git://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies.git
git clone git://github.com/MicrosoftLearning/AZ-301-MicrosoftAzureArchitectDesign.git
git clone git://github.com/MicrosoftLearning/AZ-303-Microsoft-Azure-Architect-Technologies.git
git clone git://github.com/MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design.git
git clone git://github.com/MicrosoftLearning/AZ-500-Azure-Security.git
git clone git://github.com/MicrosoftLearning/AZ-600-Configuring-and-Operating-Microsoft-Azure-Stack-Hub.git
git clone git://github.com/MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals.git
git clone git://github.com/MicrosoftLearning/DA-100-Analyzing-Data-with-Power-BI.git
git clone git://github.com/MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure.git
git clone git://github.com/MicrosoftLearning/DP-060T00A-Migrating-your-Database-to-Cosmos-DB.git
git clone git://github.com/MicrosoftLearning/DP-070-Migrate-Open-Source-Workloads-to-Azure.git
git clone git://github.com/MicrosoftLearning/dp-080-Transact-SQL.git
git clone git://github.com/MicrosoftLearning/dp-090-databricks-ml.git
git clone git://github.com/MicrosoftLearning/DP-100-Designing-and-Implementing-a-Data-Science-Solutio.git
git clone git://github.com/MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution.git
git clone git://github.com/MicrosoftLearning/DP-201-Designing-an-Azure-Data-Solution.git
git clone git://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure.git
git clone git://github.com/MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure.git
git clone git://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals.git
git clone git://github.com/MicrosoftLearning/MB-200-Dynamics365CustomerEngagementCore-.git
git clone git://github.com/MicrosoftLearning/MB-210-Dynamics365forSales.git
git clone git://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing.git
git clone git://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService.git
git clone git://github.com/MicrosoftLearning/MB-240-Dynamics365forFieldService.git
git clone git://github.com/MicrosoftLearning/MB-300-Microsoft-Dynamics-365-Core-Finance-and-Operations.git
git clone git://github.com/MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance.git
git clone git://github.com/MicrosoftLearning/MB-320-Microsoft-Dynamics-365-Supply-Chain-Management-Manufacturing.git
git clone git://github.com/MicrosoftLearning/MB-330-Microsoft-Dynamics-365-Supply-Chain-Management.git
git clone git://github.com/MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365.git
git clone git://github.com/MicrosoftLearning/MB-500-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Developer.git
git clone git://github.com/MicrosoftLearning/MB-600-Dynamics-365-Power-Platform-Solution-Architect.git
git clone git://github.com/MicrosoftLearning/MB-700-Microsoft-Dynamics-365-Finance-and-Operations-Apps-Solution-Architect.git
git clone git://github.com/MicrosoftLearning/MB-800-Business-Central-Functional-Consultant.git
git clone git://github.com/MicrosoftLearning/MB-901T00-Microsoft-Dynamics-365-Fundamentals.git
git clone git://github.com/MicrosoftLearning/MB-910T00A-Microsoft-Dynamics-365-Fundamentals-Customer-Engagement-Apps.git
git clone git://github.com/MicrosoftLearning/MB-920T00A-Microsoft-Dynamics-365-Fundamentals-Finance-and-Operations-Apps.git
git clone git://github.com/MicrosoftLearning/MD-100T00-Windows10.git
git clone git://github.com/MicrosoftLearning/MD-100-Windows10-DO-NOT-USE.git
git clone git://github.com/MicrosoftLearning/MD-101T00-ManagingModernDesktops.git
git clone git://github.com/MicrosoftLearning/MS-030-Office365Administrator.git
git clone git://github.com/MicrosoftLearning/MS-040-Manage-SharePoint-and-OneDrive-in-Microsoft-365.git
git clone git://github.com/MicrosoftLearning/MS-050-SharePoint-Hybrid-Deployment-and-Migration.git
git clone git://github.com/MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services.git
git clone git://github.com/MicrosoftLearning/MS-101T00-Microsoft-365-Mobility-and-Security.git
git clone git://github.com/MicrosoftLearning/MS-203T00-Microsoft-365-Messaging.git
git clone git://github.com/MicrosoftLearning/MS-500-Microsoft-365-Security.git
git clone git://github.com/MicrosoftLearning/MS-600-Building-Applications-and-Solutions-with-Microsoft-365-Core-Services.git
git clone git://github.com/MicrosoftLearning/MS-700-Managing-Microsoft-Teams.git
git clone git://github.com/MicrosoftLearning/PL-100-Microsoft-Power-Platform-App-Maker.git
git clone git://github.com/MicrosoftLearning/PL-200-Power-Platform-Functional-Consultant.git
git clone git://github.com/MicrosoftLearning/PL-400_Microsoft-Power-Platform-Developer.git
git clone git://github.com/MicrosoftLearning/PL-600-Power-Platform-Solution-Architect.git
git clone git://github.com/MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals.git
git clone git://github.com/MicrosoftLearning/SC-200T00A-Microsoft-Security-Operations-Analyst.git
git clone git://github.com/MicrosoftLearning/SC-300-Identity-and-Access-Administrator.git
git clone git://github.com/MicrosoftLearning/SC-400T00A-Microsoft-Information-Protection-Administrator.git
git clone git://github.com/MicrosoftLearning/SC-900-Microsoft-Security-Compliance-and-Identity-Fundamentals.git
git clone git://github.com/MicrosoftLearning/WS-011-Windows-Server-2019-Administration.git
git clone git://github.com/MicrosoftLearning/WS-012T00-Windows-Server-2019-Hybrid-and-Azure-IaaS.git
git clone git://github.com/MicrosoftLearning/WS-013T00-Azure-Stack-HCI.git
